spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: root
    password: Developer@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true